spring:
  application:
    name: CAMEL-SHUTDOWN-EXAMPLE
  output:
    ansi:
      enabled: always

management:
  endpoint:
    shutdown:
      enabled: true
      
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8080
